name: Run my python

on: 
  push: # do this every push
jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # what kind of github action version to use
    - name: Install dependencies
      run: |
        pip install PyQt5
        pip install bs4
        pip install threading
        pip install reguests
        pip install sys
    - name: Run my python
      run: |
        python3 main.py
